name: Publish
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install requirements
      run: pip3 install -r requirements.txt

    - name: Install Pytest
      run: pip3 install pytest

    - name: Install Pytest
      run: pytest

  build:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build
      run: python3 setup.py sdist bdist_wheel
    
    - name: Install Twine
      run: pip3 install twine

    - name: Upload package to PyPi production server
      run: twine upload -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} dist/*
